name: fast_ecs
description: Simple and fast Entity-Component-System (ECS) library written in Dart.
version: 0.1.0
homepage: 'https://github.com/QiXi/fast_ecs'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
